package com.example.administrator.daiylywriting.BooksSqilte;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BIG_DATA.
 */
public class BigData {

    private Long id;
    private Integer OneDayNumber;
    private String TimeDate;

    public BigData() {
    }

    public BigData(Long id) {
        this.id = id;
    }

    public BigData(Long id, Integer OneDayNumber, String TimeDate) {
        this.id = id;
        this.OneDayNumber = OneDayNumber;
        this.TimeDate = TimeDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getOneDayNumber() {
        return OneDayNumber;
    }

    public void setOneDayNumber(Integer OneDayNumber) {
        this.OneDayNumber = OneDayNumber;
    }

    public String getTimeDate() {
        return TimeDate;
    }

    public void setTimeDate(String TimeDate) {
        this.TimeDate = TimeDate;
    }

}
