package com.example.administrator.daiylywriting.BooksSqilte;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOOKS_VAULES.
 */
public class BooksVaules {

    private Long id;
    private String BookName;
    private Boolean IsDeleted;
    /** Not-null value. */
    private String BookKey;
    private String BookModel;
    private Integer BookCharpterNumbers;
    private Integer BookVauleNumbers;

    public BooksVaules() {
    }

    public BooksVaules(Long id) {
        this.id = id;
    }

    public BooksVaules(Long id, String BookName, Boolean IsDeleted, String BookKey, String BookModel, Integer BookCharpterNumbers, Integer BookVauleNumbers) {
        this.id = id;
        this.BookName = BookName;
        this.IsDeleted = IsDeleted;
        this.BookKey = BookKey;
        this.BookModel = BookModel;
        this.BookCharpterNumbers = BookCharpterNumbers;
        this.BookVauleNumbers = BookVauleNumbers;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBookName() {
        return BookName;
    }

    public void setBookName(String BookName) {
        this.BookName = BookName;
    }

    public Boolean getIsDeleted() {
        return IsDeleted;
    }

    public void setIsDeleted(Boolean IsDeleted) {
        this.IsDeleted = IsDeleted;
    }

    /** Not-null value. */
    public String getBookKey() {
        return BookKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBookKey(String BookKey) {
        this.BookKey = BookKey;
    }

    public String getBookModel() {
        return BookModel;
    }

    public void setBookModel(String BookModel) {
        this.BookModel = BookModel;
    }

    public Integer getBookCharpterNumbers() {
        return BookCharpterNumbers;
    }

    public void setBookCharpterNumbers(Integer BookCharpterNumbers) {
        this.BookCharpterNumbers = BookCharpterNumbers;
    }

    public Integer getBookVauleNumbers() {
        return BookVauleNumbers;
    }

    public void setBookVauleNumbers(Integer BookVauleNumbers) {
        this.BookVauleNumbers = BookVauleNumbers;
    }

}
