package com.example.administrator.daiylywriting.BooksSqilte;
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHARPTERS.
 */
public class Charpters {

    private Long id;
    /** Not-null value. */
    private String BookKey;
    /** Not-null value. */
    private String CharpterName;
    /** Not-null value. */
    private String CharpterKey;
    private String CharpterVaules;
    private String CreateTime;
    private Integer ChapterVauleNumbers;
    private Integer EditSpeed;
    private Boolean IsDeleted;

    public Charpters() {
    }

    public Charpters(Long id) {
        this.id = id;
    }

    public Charpters(Long id, String BookKey, String CharpterName, String CharpterKey, String CharpterVaules, String CreateTime, Integer ChapterVauleNumbers, Integer EditSpeed, Boolean IsDeleted) {
        this.id = id;
        this.BookKey = BookKey;
        this.CharpterName = CharpterName;
        this.CharpterKey = CharpterKey;
        this.CharpterVaules = CharpterVaules;
        this.CreateTime = CreateTime;
        this.ChapterVauleNumbers = ChapterVauleNumbers;
        this.EditSpeed = EditSpeed;
        this.IsDeleted = IsDeleted;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBookKey() {
        return BookKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBookKey(String BookKey) {
        this.BookKey = BookKey;
    }

    /** Not-null value. */
    public String getCharpterName() {
        return CharpterName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCharpterName(String CharpterName) {
        this.CharpterName = CharpterName;
    }

    /** Not-null value. */
    public String getCharpterKey() {
        return CharpterKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCharpterKey(String CharpterKey) {
        this.CharpterKey = CharpterKey;
    }

    public String getCharpterVaules() {
        return CharpterVaules;
    }

    public void setCharpterVaules(String CharpterVaules) {
        this.CharpterVaules = CharpterVaules;
    }

    public String getCreateTime() {
        return CreateTime;
    }

    public void setCreateTime(String CreateTime) {
        this.CreateTime = CreateTime;
    }

    public Integer getChapterVauleNumbers() {
        return ChapterVauleNumbers;
    }

    public void setChapterVauleNumbers(Integer ChapterVauleNumbers) {
        this.ChapterVauleNumbers = ChapterVauleNumbers;
    }

    public Integer getEditSpeed() {
        return EditSpeed;
    }

    public void setEditSpeed(Integer EditSpeed) {
        this.EditSpeed = EditSpeed;
    }

    public Boolean getIsDeleted() {
        return IsDeleted;
    }

    public void setIsDeleted(Boolean IsDeleted) {
        this.IsDeleted = IsDeleted;
    }

}
