package com.example.administrator.daiylywriting.BooksSqilte;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DRAFT_BOX.
 */
public class DraftBox {

    private String DraftVaule;

    public DraftBox() {
    }

    public DraftBox(String DraftVaule) {
        this.DraftVaule = DraftVaule;
    }

    public String getDraftVaule() {
        return DraftVaule;
    }

    public void setDraftVaule(String DraftVaule) {
        this.DraftVaule = DraftVaule;
    }

}
