package com.example.administrator.daiylywriting.BooksSqilte;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table NOW_HAPPENTS.
*/
public class NowHappentsDao extends AbstractDao<NowHappents, Long> {

    public static final String TABLENAME = "NOW_HAPPENTS";

    /**
     * Properties of entity NowHappents.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property News = new Property(1, String.class, "News", false, "NEWS");
        public final static Property Times = new Property(2, String.class, "times", false, "TIMES");
    };


    public NowHappentsDao(DaoConfig config) {
        super(config);
    }
    
    public NowHappentsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'NOW_HAPPENTS' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NEWS' TEXT," + // 1: News
                "'TIMES' TEXT);"); // 2: times
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'NOW_HAPPENTS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, NowHappents entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String News = entity.getNews();
        if (News != null) {
            stmt.bindString(2, News);
        }
 
        String times = entity.getTimes();
        if (times != null) {
            stmt.bindString(3, times);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public NowHappents readEntity(Cursor cursor, int offset) {
        NowHappents entity = new NowHappents( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // News
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // times
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, NowHappents entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNews(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTimes(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(NowHappents entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(NowHappents entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
