package com.example.administrator.daiylywriting.BooksSqilte;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOW_HAPPENTS.
 */
public class NowHappents {

    private Long id;
    private String News;
    private String times;

    public NowHappents() {
    }

    public NowHappents(Long id) {
        this.id = id;
    }

    public NowHappents(Long id, String News, String times) {
        this.id = id;
        this.News = News;
        this.times = times;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNews() {
        return News;
    }

    public void setNews(String News) {
        this.News = News;
    }

    public String getTimes() {
        return times;
    }

    public void setTimes(String times) {
        this.times = times;
    }

}
