package com.example.administrator.daiylywriting.BooksSqilte;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_VAULE.
 */
public class UserVaule {

    private Long id;
    private Integer Exp;
    private byte[] UserImage;
    private String CreateTime;
    private String UserName;

    public UserVaule() {
    }

    public UserVaule(Long id) {
        this.id = id;
    }

    public UserVaule(Long id, Integer Exp, byte[] UserImage, String CreateTime, String UserName) {
        this.id = id;
        this.Exp = Exp;
        this.UserImage = UserImage;
        this.CreateTime = CreateTime;
        this.UserName = UserName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getExp() {
        return Exp;
    }

    public void setExp(Integer Exp) {
        this.Exp = Exp;
    }

    public byte[] getUserImage() {
        return UserImage;
    }

    public void setUserImage(byte[] UserImage) {
        this.UserImage = UserImage;
    }

    public String getCreateTime() {
        return CreateTime;
    }

    public void setCreateTime(String CreateTime) {
        this.CreateTime = CreateTime;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

}
