package com.example.administrator.daiylywriting.BooksSqilte;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WEB_DATA.
 */
public class WebData {

    private Long id;
    private Integer ClickNumber;
    private Integer LikeNumber;
    private String BookName;
    private String TimeDate;

    public WebData() {
    }

    public WebData(Long id) {
        this.id = id;
    }

    public WebData(Long id, Integer ClickNumber, Integer LikeNumber, String BookName, String TimeDate) {
        this.id = id;
        this.ClickNumber = ClickNumber;
        this.LikeNumber = LikeNumber;
        this.BookName = BookName;
        this.TimeDate = TimeDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getClickNumber() {
        return ClickNumber;
    }

    public void setClickNumber(Integer ClickNumber) {
        this.ClickNumber = ClickNumber;
    }

    public Integer getLikeNumber() {
        return LikeNumber;
    }

    public void setLikeNumber(Integer LikeNumber) {
        this.LikeNumber = LikeNumber;
    }

    public String getBookName() {
        return BookName;
    }

    public void setBookName(String BookName) {
        this.BookName = BookName;
    }

    public String getTimeDate() {
        return TimeDate;
    }

    public void setTimeDate(String TimeDate) {
        this.TimeDate = TimeDate;
    }

}
